arch: s390x
os:   linux

sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=sandeepbatta/ibm-cloud-dev-nginx
    - REGISTRY_USER=sandeepbatta
    # REGISTRY_PASS=...
    - secret: "this is a secret to push a docker image to hub.docker.com"

before_script:
  - version=IBM_CLOUDDEV_VERSION
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
